version: '3.8'
services:
  bd:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db1
      - POSTGRES_USER=volontare
      - POSTGRES_PASSWORD=Dtcyf2021
